package com.design.dao;

import com.design.entity.AssignmentBook;
import com.design.entity.AssignmentBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssignmentBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int countByExample(AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int deleteByExample(AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int insert(AssignmentBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int insertSelective(AssignmentBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    List<AssignmentBook> selectByExample(AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    AssignmentBook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssignmentBook record, @Param("example") AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssignmentBook record, @Param("example") AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssignmentBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssignmentBook record);

    AssignmentBook getAssignmentBookById(String assignmentbookid);

    int insertassignmentBook(AssignmentBook assignmentBook);

    void updateAssignmentBook(AssignmentBook assignmentBook);
}