package com.design.dao;

import com.design.entity.Office;
import com.design.entity.OfficeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;


public interface OfficeMapper<T> {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int countByExample(OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int deleteByExample(OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int insert(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int insertSelective(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    List<Office> selectByExample(OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    Office selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Office record, @Param("example") OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Office record, @Param("example") OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Office record);

    List<Office> findAllOffice();

    Office get(String id);

    List<Office> get1(String id);


}