package com.design.dao;

import com.design.entity.User;
import com.design.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

//    List<User> getuserListByPageAndRows(@Param("page") int page,@Param("rows") int rows);

    int getAllCount();

    List<User> getuserListByPageAndRows(@Param("page")int page, @Param("rows")int rows, @Param("selectname")String selectname);

    int getAllCountBySelectname(String selectname);

    String getPasswordByid(Integer id);

    int getUserCountByidentityNumber(String identityNumber);

    int getUserCountByusername(String username);

    int insertUserInfoAll(User user);

//    void deleteUserRoleForm(String delflag, String userid, String identitysid, String grade, String collegeid, String majorid, String roleId);

    void deleteUserRoleForm(User user1);

    List<User> getGradeListById(String userid);

    String getrolenameByroleid(@Param("roleId")String roleId);

    int getuserRoleCount(@Param("userid")String userid, @Param("delflag") String delflag);

    User getuiaAllByUiaId(@Param("uiaid")String uiaid);

    User getUserAllInfoByUserId(@Param("uiaid") String uiaid,@Param("userid")String userid);

    void updateUserAllInfoByPrimaryKey(User user);

    List<User> findAllUser();

    String getuiaIdByAllInformation(@Param("userid")String userid,@Param("grade")String grade, @Param("collegeid") String collegeid, @Param("majorid")String majorid, @Param("roleId")String roleId);

    List<User> getallSessionIdByAllInformation(@Param("uiaid")String uiaid, @Param("delFlag")String delFlag);

    void insertUserOnLineSession(@Param("uiaid")String uiaid, @Param("Sessionid") String Sessionid);

    void deleteSessionid(@Param("Sessionid")String Sessionid);


//    void updateTaskByUserId(User user2);

//    User getUserByUserId(String userid);
}
